"use client";
import Image from "next/image";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { CrmNavigation } from "@/app/components/crm-navigation";
import "./agent.css";
import "./agent-layout.css";

type Provider={id:string;provider:string;model:string;api_key_ref:string;base_url:string|null;enabled:boolean;priority:number};
type Version={version:number;file_name:string;status:string};
type Playbook={id:string;name:string;description:string|null;active_version:number|null;active:boolean;versions:Version[]};
type Control={globalMode:string;capabilityLevels:Record<string,string>;killSwitch:boolean;outboundKillSwitch:boolean;simulationMode:boolean};
type Config={persona:{persona_name:string;tone:Record<string,number>;sales:Record<string,number>;provider_preferences?:{provider?:string;model?:string}};control:{global_mode:string;capability_levels:Record<string,string>;kill_switch:boolean;outbound_kill_switch:boolean;simulation_mode:boolean}};
const names:Record<string,string>={directness:"Objetividade",formality:"Formalidade",didacticism:"Didática",persuasion:"Persuasão",humor:"Humor",emojiUsage:"Uso de emojis",messageLength:"Tamanho da mensagem",commercialIntensity:"Intensidade comercial",objectionHandling:"Tratamento de objeções",followupIntensity:"Intensidade de follow-up",closingIntensity:"Intensidade de fechamento",reactivationIntensity:"Intensidade de reativação"};
const levels:Record<string,string>={disabled:"Desativado",suggest:"Sugere",approval:"Exige aprovação",automatic:"Automático"};
async function json<T>(response:Response):Promise<T>{const data=await response.json().catch(()=>({})) as T&{error?:string};if(!response.ok)throw new Error(data.error||"Operação indisponível.");return data}

export default function AgentSettingsPage(){
 const[config,setConfig]=useState<Config|null>(null),[providers,setProviders]=useState<Provider[]>([]),[playbooks,setPlaybooks]=useState<Playbook[]>([]),[control,setControl]=useState<Control|null>(null);
 const[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState("");
 const[providerForm,setProviderForm]=useState({provider:"",model:"",apiKeyRef:"",baseUrl:"",priority:100});
 const load=useCallback(async()=>{setLoading(true);setError("");setConfig(null);setControl(null);try{const[c,p,b,k]=await Promise.all([fetch("/api/agent/brain/config").then(json<Config>),fetch("/api/agent/brain/providers").then(json<{providers:Provider[]}>),fetch("/api/agent/playbooks").then(json<{playbooks:Playbook[]}>),fetch("/api/agent/control").then(json<Control>)]);setConfig(c);setProviders(p.providers);setPlaybooks(b.playbooks);setControl(k)}catch(reason){setError(reason instanceof Error?reason.message:"Configuração indisponível.")}finally{setLoading(false)}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 const scale=(group:"tone"|"sales",key:string,value:number)=>config&&setConfig({...config,persona:{...config.persona,[group]:{...config.persona[group],[key]:value}}});
 const persona=async()=>{if(!config)return;setBusy("persona");setError("");try{setConfig(await fetch("/api/agent/brain/config",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({personaName:config.persona.persona_name,tone:config.persona.tone,sales:config.persona.sales,provider:config.persona.provider_preferences?.provider||null,model:config.persona.provider_preferences?.model||null})}).then(json<Config>));setMessage("Persona salva.")}catch(e){setError(e instanceof Error?e.message:"Falha ao salvar.")}finally{setBusy("")}};
 const addProvider=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy("provider");setError("");try{await fetch("/api/agent/brain/providers",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...providerForm,baseUrl:providerForm.baseUrl.trim()||null,enabled:false})}).then(json);setProviderForm({provider:"",model:"",apiKeyRef:"",baseUrl:"",priority:100});setMessage("Provider salvo inativo.");await load()}catch(reason){setError(reason instanceof Error?reason.message:"Falha ao salvar provider.")}finally{setBusy("")}};
 const toggleProvider=async(p:Provider)=>{setBusy(p.id);setError("");try{await fetch("/api/agent/brain/providers",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:p.id,enabled:!p.enabled})}).then(json);await load()}catch(e){setError(e instanceof Error?e.message:"Falha ao atualizar provider.")}finally{setBusy("")}};
 const upload=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;setBusy("playbook");setError("");try{await fetch("/api/agent/playbooks",{method:"POST",body:new FormData(form)}).then(json);form.reset();setMessage("Playbook enviado.");await load()}catch(reason){setError(reason instanceof Error?reason.message:"Falha no upload.")}finally{setBusy("")}};
 const togglePlaybook=async(p:Playbook)=>{const version=p.active_version||p.versions[0]?.version;if(!version){setError("Playbook sem versão disponível.");return}setBusy(p.id);try{await fetch("/api/agent/playbooks",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({playbookId:p.id,version,active:!p.active})}).then(json);await load()}catch(e){setError(e instanceof Error?e.message:"Falha ao atualizar playbook.")}finally{setBusy("")}};
 const capabilities=control?.capabilityLevels||config?.control.capability_levels||{};
 const simulationMode=control?.simulationMode??config?.control.simulation_mode;
 const outboundKillSwitch=control?.outboundKillSwitch??config?.control.outbound_kill_switch;
 const killSwitch=control?.killSwitch??config?.control.kill_switch;
 const outboundBlocked=simulationMode===true||outboundKillSwitch===true||killSwitch===true;
 return <main className="agent-settings"><aside className="agent-sidebar"><div className="agent-brand"><Image src="/monteiro-logo.png" alt="Monteiro CRM" width={58} height={64}/><b>MONTEIRO</b><span>CRM</span></div><CrmNavigation/><div className="agent-user"><i>FM</i><div><b>Franklin Monteiro</b><span>Corretor + Gestor</span></div></div></aside><section className="agent-content"><header><span>Configurações / Agente</span><h1>Cérebro Comercial</h1><p>Controles, conhecimento e comportamento do Agente Monteiro.</p></header>
 <div className="agent-safety"><b className={simulationMode===true?"safe":simulationMode===false?"blocked":""}>SIMULATION MODE {simulationMode===undefined?"INDETERMINADO":simulationMode?"ON":"OFF"}</b><b className={outboundBlocked?"blocked":""}>OUTBOUND REAL {outboundBlocked?"OFF":"INDETERMINADO"}</b><b>OUTBOUND KILL SWITCH {outboundKillSwitch===undefined?"INDETERMINADO":outboundKillSwitch?"ATIVO":"INATIVO"}</b><b>KILL SWITCH GLOBAL {killSwitch===undefined?"INDETERMINADO":killSwitch?"ATIVO":"INATIVO"}</b></div>
 {loading&&<p className="notice">Carregando configurações...</p>}{error&&<p className="notice error" role="alert">{error} <button className="link" onClick={load}>Tentar novamente</button></p>}{message&&<p className="notice success">{message}</p>}
 {config&&<section className="panel"><div className="heading"><div><h2>Persona</h2><p>Ajuste tom e intensidade comercial.</p></div><button onClick={persona} disabled={busy==="persona"}>{busy==="persona"?"Salvando...":"Salvar persona"}</button></div><label>Nome da persona<input value={config.persona.persona_name} onChange={e=>setConfig({...config,persona:{...config.persona,persona_name:e.target.value}})}/></label><div className="grid">{[...Object.entries(config.persona.tone).map(([k,v])=>["tone",k,v] as const),...Object.entries(config.persona.sales).map(([k,v])=>["sales",k,v] as const)].map(([g,k,v])=><label className="scale" key={g+k}><span>{names[k]||k}<output>{v}</output></span><input type="range" min="0" max="10" value={v} onChange={e=>scale(g,k,Number(e.target.value))}/></label>)}</div></section>}
 <section className="panel"><div className="heading"><div><h2>Providers</h2><p>Referencie variável dedicada `AGENT_LLM_API_KEY_*`. Nunca cole chave secreta.</p></div></div><form className="form providers" onSubmit={addProvider}><label>Provider<input required value={providerForm.provider} onChange={e=>setProviderForm({...providerForm,provider:e.target.value})}/></label><label>Modelo<input required value={providerForm.model} onChange={e=>setProviderForm({...providerForm,model:e.target.value})}/></label><label>Referência da chave<input required pattern="AGENT_LLM_API_KEY_[A-Z0-9_]+" placeholder="AGENT_LLM_API_KEY_GROQ" value={providerForm.apiKeyRef} onChange={e=>setProviderForm({...providerForm,apiKeyRef:e.target.value})}/></label><label>Base URL HTTPS<input type="url" pattern="https://.*" value={providerForm.baseUrl} onChange={e=>setProviderForm({...providerForm,baseUrl:e.target.value})}/></label><label>Prioridade<input type="number" min="0" value={providerForm.priority} onChange={e=>setProviderForm({...providerForm,priority:Number(e.target.value)})}/></label><button disabled={busy==="provider"}>Adicionar inativo</button></form><div className="list">{providers.length?providers.map(p=><article key={p.id}><div><strong>{p.priority}. {p.provider} / {p.model}</strong><small>{p.api_key_ref}{p.base_url?` · ${p.base_url}`:""}</small></div><span className={p.enabled?"status active":"status"}>{p.enabled?"Ativo":"Inativo"}</span><button className="secondary" disabled={busy===p.id} onClick={()=>toggleProvider(p)}>{p.enabled?"Desativar":"Ativar"}</button></article>):!loading&&<p className="empty">Nenhum provider. Fallback determinístico disponível.</p>}</div></section>
 <section className="panel"><div className="heading"><div><h2>Playbooks</h2><p>PDF, TXT ou MD. Máximo 25 MB.</p></div></div><form className="form playbooks" onSubmit={upload}><label>Nome<input name="name" required/></label><label>Descrição<input name="description"/></label><label>Arquivo<input name="file" type="file" required accept=".pdf,.txt,.md,application/pdf,text/plain,text/markdown"/></label><button disabled={busy==="playbook"}>Enviar playbook</button></form><div className="list">{playbooks.length?playbooks.map(p=><article key={p.id}><div><strong>{p.name}</strong><small>{p.description||"Sem descrição"} · {p.versions.length} versão(ões)</small></div><span className={p.active?"status active":"status"}>{p.active?`Ativo v${p.active_version}`:"Inativo"}</span><button className="secondary" disabled={busy===p.id} onClick={()=>togglePlaybook(p)}>{p.active?"Desativar":"Ativar última"}</button></article>):!loading&&<p className="empty">Nenhum playbook enviado.</p>}</div></section>
 <section className="panel"><div className="heading"><div><h2>Autonomia e capacidades</h2><p>Leitura dos controles ativos.</p></div><span className="status">Global: {levels[control?.globalMode||config?.control.global_mode||""]||"Indisponível"}</span></div><div className="capabilities">{Object.entries(capabilities).map(([k,v])=><div key={k}><span>{names[k]||k}</span><strong>{levels[v]||v}</strong></div>)}{!loading&&!Object.keys(capabilities).length&&<p className="empty">Nenhuma capacidade configurada.</p>}</div></section>
 <section className="panel"><div className="heading"><div><h2>Human Takeover</h2><p>Controle por conversa; não altera outbound real.</p></div></div><div className="modes"><div><strong>AUTO</strong><span>Agente atua dentro das políticas.</span></div><div><strong>HUMAN_TAKEOVER</strong><span>Humano assume; agente não responde.</span></div><div><strong>OBSERVE_ONLY</strong><span>Agente analisa sem executar.</span></div><div><strong>PAUSED</strong><span>Processamento suspenso.</span></div></div></section>
 </section></main>}
