"use client";
import Image from "next/image";
import { FormEvent, useEffect, useState } from "react";
import { CrmNavigation } from "../components/crm-navigation";
import "./ccas.css";

type Cca={id:number;name:string;responsible_name:string;phone:string;whatsapp:string;email?:string;region?:string;notes?:string;active:boolean};
const empty={name:"",responsible_name:"",phone:"",whatsapp:"",email:"",region:"",notes:""};

export default function CcasPage(){
 const [items,setItems]=useState<Cca[]>([]); const [form,setForm]=useState(empty); const [open,setOpen]=useState(false); const [message,setMessage]=useState("");
 const load=()=>fetch("/api/ccas").then(r=>r.json()).then(data=>setItems(Array.isArray(data)?data:[]));
 useEffect(()=>{load()},[]);
 async function save(e:FormEvent){e.preventDefault();setMessage("Salvando...");const r=await fetch("/api/ccas",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const data=await r.json();if(!r.ok){setMessage(data.error||"Não foi possível salvar.");return}setForm(empty);setOpen(false);setMessage("CCA cadastrado com sucesso.");load()}
 async function toggle(item:Cca){await fetch("/api/ccas",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,active:!item.active})});load()}
 return <main className="cca-shell"><aside className="cca-sidebar"><div className="cca-brand"><Image src="/monteiro-logo.png" alt="Monteiro CRM" width={58} height={64}/><b>MONTEIRO</b><span>CRM</span></div><CrmNavigation/><div className="cca-user"><i>FM</i><div><b>Franklin Monteiro</b><span>Corretor + Gestor</span></div></div></aside><section className="cca-main"><header className="cca-header"><div><span>Parceiros de crédito imobiliário</span><h1>Central de CCA</h1><p>Cadastre responsáveis, contatos e canais usados para envio das análises.</p></div><button onClick={()=>setOpen(v=>!v)}>＋ Cadastrar CCA</button></header><div className="cca-content">{message&&<p className="cca-message">{message}</p>}{open&&<form className="cca-form" onSubmit={save}><label>Nome do CCA<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Responsável<input value={form.responsible_name} onChange={e=>setForm({...form,responsible_name:e.target.value})} required/></label><label>Telefone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} required/></label><label>WhatsApp<input value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value})}/></label><label>E-mail<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Região<input value={form.region} onChange={e=>setForm({...form,region:e.target.value})}/></label><label className="wide">Observações<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button type="submit">Salvar CCA</button></form>}<section className="cca-list"><header><div><span>Correspondentes cadastrados</span><h2>{items.length} CCA{items.length===1?"":"s"}</h2></div></header>{!items.length&&<div className="cca-empty"><b>Nenhum CCA cadastrado</b><span>Cadastre o primeiro correspondente para habilitar o envio de análises.</span></div>}{items.map(item=><article key={item.id} className={item.active?"":"inactive"}><div><b>{item.name}</b><span>{item.responsible_name} · {item.region||"Região não informada"}</span><small>{item.email||"E-mail não informado"}</small></div><div className="cca-contact"><a href={`tel:${item.phone}`}>☎ Ligar</a><a className="whatsapp" href={`https://wa.me/55${item.whatsapp.replace(/\D/g,"").replace(/^55/,"")}`} target="_blank" rel="noreferrer"><Image src="/whatsapp.svg" alt="WhatsApp" width={17} height={17}/> WhatsApp</a><button onClick={()=>toggle(item)}>{item.active?"Desativar":"Ativar"}</button></div></article>)}</section></div></section></main>}
