create table if not exists public.agent_llm_providers (
  id uuid primary key default gen_random_uuid(),
  provider text not null,
  model text not null,
  api_key_ref text not null,
  base_url text,
  enabled boolean not null default false,
  priority integer not null default 100 check (priority >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(provider, model, api_key_ref)
);

create table if not exists public.agent_conversation_summaries (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  conversation_id uuid references public.whatsapp_conversations(id) on delete cascade,
  summary text not null,
  last_message_id bigint references public.whatsapp_messages(id) on delete set null,
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  unique nulls not distinct (client_id, conversation_id, version)
);
create index if not exists agent_conversation_summaries_conversation_idx on public.agent_conversation_summaries(conversation_id);
create index if not exists agent_conversation_summaries_last_message_idx on public.agent_conversation_summaries(last_message_id);

create table if not exists public.agent_client_knowledge (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  key text not null,
  value jsonb,
  knowledge_type text not null check (knowledge_type in ('FACT','INFERENCE','UNKNOWN')),
  source_message_id bigint references public.whatsapp_messages(id) on delete set null,
  confidence numeric(4,3) not null check (confidence between 0 and 1),
  active boolean not null default true,
  superseded_by bigint references public.agent_client_knowledge(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists agent_client_knowledge_active_key_idx
  on public.agent_client_knowledge(client_id, key) where active;
create index if not exists agent_client_knowledge_source_message_idx on public.agent_client_knowledge(source_message_id);
create unique index if not exists agent_client_knowledge_superseded_idx on public.agent_client_knowledge(superseded_by) where superseded_by is not null;

create or replace function public.upsert_agent_client_knowledge(
  p_client_id bigint,
  p_key text,
  p_value jsonb,
  p_knowledge_type text,
  p_source_message_id bigint,
  p_confidence numeric(4,3)
) returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_current_id bigint;
  v_current_type text;
  v_new_id bigint;
  v_source_client_id bigint;
begin
  if p_key is null or btrim(p_key) = '' or p_knowledge_type not in ('FACT','INFERENCE','UNKNOWN') or p_confidence is null or p_confidence < 0 or p_confidence > 1 then
    raise exception 'Invalid agent knowledge payload';
  end if;
  p_key := lower(btrim(p_key));
  perform pg_advisory_xact_lock(hashtextextended(p_client_id::text || ':' || p_key, 0));
  if p_source_message_id is not null then
    select client_id into v_source_client_id from public.whatsapp_messages where id = p_source_message_id;
    if v_source_client_id is distinct from p_client_id then raise exception 'Source message does not belong to client'; end if;
  end if;
  select id, knowledge_type into v_current_id, v_current_type
  from public.agent_client_knowledge
  where client_id = p_client_id and key = p_key and active
  for update;
  if v_current_type = 'FACT' and p_knowledge_type = 'INFERENCE' then return v_current_id; end if;
  if v_current_id is not null and exists (
    select 1 from public.agent_client_knowledge
    where id = v_current_id and knowledge_type = p_knowledge_type and value is not distinct from p_value
      and source_message_id is not distinct from p_source_message_id and confidence = p_confidence
  ) then return v_current_id; end if;
  if v_current_id is not null then
    update public.agent_client_knowledge set active = false, updated_at = now() where id = v_current_id;
  end if;
  insert into public.agent_client_knowledge(client_id,key,value,knowledge_type,source_message_id,confidence)
  values(p_client_id,p_key,p_value,p_knowledge_type,p_source_message_id,p_confidence)
  returning id into v_new_id;
  if v_current_id is not null then update public.agent_client_knowledge set superseded_by = v_new_id where id = v_current_id; end if;
  return v_new_id;
end;
$$;
revoke all on function public.upsert_agent_client_knowledge(bigint,text,jsonb,text,bigint,numeric) from public, anon, authenticated;
grant execute on function public.upsert_agent_client_knowledge(bigint,text,jsonb,text,bigint,numeric) to service_role;

create or replace function public.append_agent_conversation_summary(
  p_client_id bigint,
  p_conversation_id uuid,
  p_summary text,
  p_last_message_id bigint
) returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_version integer;
  v_id bigint;
begin
  if p_summary is null or btrim(p_summary) = '' then raise exception 'Summary is required'; end if;
  perform pg_advisory_xact_lock(hashtextextended(p_client_id::text || ':' || coalesce(p_conversation_id::text, 'none'), 0));
  if p_conversation_id is not null and not exists (
    select 1 from public.whatsapp_conversations where id = p_conversation_id and client_id = p_client_id
  ) then raise exception 'Conversation does not belong to client'; end if;
  if p_last_message_id is not null and not exists (
    select 1 from public.whatsapp_messages
    where id = p_last_message_id and client_id = p_client_id
      and (p_conversation_id is null or conversation_id = p_conversation_id)
  ) then raise exception 'Message does not belong to client conversation'; end if;
  select coalesce(max(version), 0) + 1 into v_version
  from public.agent_conversation_summaries
  where client_id = p_client_id and conversation_id is not distinct from p_conversation_id;
  insert into public.agent_conversation_summaries(client_id,conversation_id,summary,last_message_id,version)
  values(p_client_id,p_conversation_id,p_summary,p_last_message_id,v_version)
  returning id into v_id;
  return v_id;
end;
$$;
revoke all on function public.append_agent_conversation_summary(bigint,uuid,text,bigint) from public, anon, authenticated;
grant execute on function public.append_agent_conversation_summary(bigint,uuid,text,bigint) to service_role;

create table if not exists public.agent_playbooks (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  active_version integer,
  active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (not active or active_version is not null)
);

create table if not exists public.agent_playbook_versions (
  id uuid primary key default gen_random_uuid(),
  playbook_id uuid not null references public.agent_playbooks(id) on delete cascade,
  version integer not null check (version > 0),
  file_name text not null,
  storage_path text not null,
  mime_type text not null,
  status text not null default 'uploaded' check (status in ('uploaded','analyzing','review','active','failed','inactive')),
  analysis_error text,
  created_at timestamptz not null default now(),
  analyzed_at timestamptz,
  unique(playbook_id, version)
);
alter table public.agent_playbooks
  add constraint agent_playbooks_active_version_fkey
  foreign key(id, active_version) references public.agent_playbook_versions(playbook_id, version)
  deferrable initially deferred;
create index if not exists agent_playbook_versions_playbook_idx on public.agent_playbook_versions(playbook_id);

create table if not exists public.agent_playbook_principles (
  id bigint generated by default as identity primary key,
  playbook_version_id uuid not null references public.agent_playbook_versions(id) on delete cascade,
  technique text not null,
  goal text not null,
  stage text not null,
  applicable_when text[] not null default '{}',
  avoid_when text[] not null default '{}',
  example text,
  risk text,
  reviewed boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists agent_playbook_principles_version_idx on public.agent_playbook_principles(playbook_version_id);

alter table public.agent_persona_config
  add column if not exists provider_preferences jsonb not null default '{"provider":null,"model":null}'::jsonb;

alter table public.agent_llm_providers enable row level security;
alter table public.agent_conversation_summaries enable row level security;
alter table public.agent_client_knowledge enable row level security;
alter table public.agent_playbooks enable row level security;
alter table public.agent_playbook_versions enable row level security;
alter table public.agent_playbook_principles enable row level security;

revoke all on public.agent_llm_providers, public.agent_conversation_summaries,
  public.agent_client_knowledge, public.agent_playbooks,
  public.agent_playbook_versions, public.agent_playbook_principles
  from public, anon, authenticated;
grant all on public.agent_llm_providers, public.agent_conversation_summaries,
  public.agent_client_knowledge, public.agent_playbooks,
  public.agent_playbook_versions, public.agent_playbook_principles
  to service_role;
grant usage, select on sequence public.agent_conversation_summaries_id_seq,
  public.agent_client_knowledge_id_seq, public.agent_playbook_principles_id_seq
  to service_role;

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('agent-playbooks', 'agent-playbooks', false, 26214400,
  array['application/pdf','text/plain','text/markdown'])
on conflict (id) do update set public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
