create table if not exists public.cca_partners (
  id bigint generated by default as identity primary key,
  name text not null unique,
  responsible_name text not null,
  phone text not null,
  whatsapp text not null,
  email text,
  region text,
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_cca_partners_active_name on public.cca_partners(active, name);
alter table public.cca_partners enable row level security;
grant select, insert, update, delete on table public.cca_partners to service_role;
grant usage, select on sequence public.cca_partners_id_seq to service_role;
