alter table public.clients
  add column if not exists can_contact boolean not null default true,
  add column if not exists do_not_contact boolean not null default false,
  add column if not exists opt_out_at timestamptz;

create table if not exists public.agent_tasks (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete cascade,
  task_type text not null,
  priority text not null default 'P3' check (priority in ('P0','P1','P2','P3','P4','P5')),
  status text not null default 'pending' check (status in ('pending','running','completed','failed','cancelled')),
  due_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb,
  attempts integer not null default 0 check (attempts >= 0),
  max_attempts integer not null default 3 check (max_attempts > 0),
  idempotency_key text not null unique,
  correlation_id uuid not null default gen_random_uuid(),
  last_error text,
  locked_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_agent_tasks_queue
  on public.agent_tasks(status, priority, due_at, created_at);
create index if not exists idx_agent_tasks_client on public.agent_tasks(client_id, created_at desc);

create table if not exists public.agent_events (
  id bigint generated by default as identity primary key,
  event_id uuid not null default gen_random_uuid() unique,
  client_id bigint references public.clients(id) on delete cascade,
  entity_type text not null,
  entity_id text,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  correlation_id uuid not null default gen_random_uuid(),
  idempotency_key text,
  actor_type text not null default 'system',
  actor_id text,
  occurred_at timestamptz not null default now()
);
create index if not exists idx_agent_events_client on public.agent_events(client_id, occurred_at desc);
create index if not exists idx_agent_events_correlation on public.agent_events(correlation_id, occurred_at);
create unique index if not exists idx_agent_events_idempotency
  on public.agent_events(idempotency_key) where idempotency_key is not null;

create table if not exists public.agent_audit_logs (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete set null,
  correlation_id uuid not null,
  idempotency_key text,
  phase text not null check (phase in ('decision','policy','confidence','execution','read_back','error')),
  action_type text not null,
  status text not null,
  input jsonb not null default '{}'::jsonb,
  output jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_agent_audit_correlation on public.agent_audit_logs(correlation_id, created_at);

create table if not exists public.agent_action_executions (
  id bigint generated by default as identity primary key,
  idempotency_key text not null unique,
  client_id bigint references public.clients(id) on delete set null,
  correlation_id uuid not null default gen_random_uuid(),
  action_type text not null,
  status text not null default 'reserved' check (status in ('reserved','simulated','executed','failed','blocked')),
  request jsonb not null default '{}'::jsonb,
  result jsonb not null default '{}'::jsonb,
  attempts integer not null default 1 check (attempts > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.agent_autonomy_config (
  id smallint primary key default 1 check (id = 1),
  global_mode text not null default 'suggest' check (global_mode in ('disabled','suggest','approval','automatic')),
  capability_levels jsonb not null default '{}'::jsonb,
  kill_switch boolean not null default false,
  outbound_kill_switch boolean not null default false,
  simulation_mode boolean not null default true,
  confidence_thresholds jsonb not null default '{"suggest":0.55,"approval":0.75,"automatic":0.9}'::jsonb,
  allowed_contact_start smallint not null default 8 check (allowed_contact_start between 0 and 23),
  allowed_contact_end smallint not null default 20 check (allowed_contact_end between 1 and 24),
  updated_by text,
  updated_at timestamptz not null default now()
);
insert into public.agent_autonomy_config(id) values (1) on conflict (id) do nothing;

create table if not exists public.agent_human_escalations (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete cascade,
  correlation_id uuid not null default gen_random_uuid(),
  reason text not null,
  context jsonb not null default '{}'::jsonb,
  status text not null default 'open' check (status in ('open','resolved','dismissed')),
  resolved_by text,
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);

create or replace function public.prevent_agent_ledger_mutation()
returns trigger language plpgsql set search_path = public as $$
begin
  raise exception 'Registros de auditoria do agente sao imutaveis';
end;
$$;

drop trigger if exists trg_agent_events_immutable on public.agent_events;
create trigger trg_agent_events_immutable before update or delete on public.agent_events
for each row execute function public.prevent_agent_ledger_mutation();
drop trigger if exists trg_agent_audit_immutable on public.agent_audit_logs;
create trigger trg_agent_audit_immutable before update or delete on public.agent_audit_logs
for each row execute function public.prevent_agent_ledger_mutation();

create or replace function public.enqueue_agent_task(
  p_client_id bigint,
  p_task_type text,
  p_priority text,
  p_due_at timestamptz,
  p_payload jsonb,
  p_idempotency_key text
) returns public.agent_tasks
language plpgsql security invoker set search_path = public as $$
declare result public.agent_tasks;
begin
  if p_idempotency_key is null or length(trim(p_idempotency_key)) < 8 then
    raise exception 'Chave de idempotencia invalida';
  end if;
  insert into public.agent_tasks(client_id, task_type, priority, due_at, payload, idempotency_key)
  values(p_client_id, p_task_type, coalesce(p_priority, 'P3'), coalesce(p_due_at, now()), coalesce(p_payload, '{}'::jsonb), p_idempotency_key)
  on conflict (idempotency_key) do update set idempotency_key = excluded.idempotency_key
  returning * into result;
  return result;
end;
$$;

alter table public.agent_tasks enable row level security;
alter table public.agent_events enable row level security;
alter table public.agent_audit_logs enable row level security;
alter table public.agent_action_executions enable row level security;
alter table public.agent_autonomy_config enable row level security;
alter table public.agent_human_escalations enable row level security;

revoke all on public.agent_tasks, public.agent_events, public.agent_audit_logs,
  public.agent_action_executions, public.agent_autonomy_config, public.agent_human_escalations
  from public, anon, authenticated;
grant all on public.agent_tasks, public.agent_events, public.agent_audit_logs,
  public.agent_action_executions, public.agent_autonomy_config, public.agent_human_escalations
  to service_role;
revoke execute on function public.enqueue_agent_task(bigint,text,text,timestamptz,jsonb,text)
  from public, anon, authenticated;
grant execute on function public.enqueue_agent_task(bigint,text,text,timestamptz,jsonb,text)
  to service_role;
