create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null unique,
  email text,
  sex text,
  marital_status text,
  profession text,
  income numeric(14,2),
  region_interest text,
  origin_type text not null,
  origin_detail text,
  project_interest text,
  funnel_stage text not null default 'Novo lead',
  finance_stage text not null default 'Não iniciado',
  post_sale_stage text,
  next_action text,
  next_action_at timestamptz,
  data_quality text not null default 'validado',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.builders (
  id bigint generated by default as identity primary key,
  name text not null unique,
  category text not null,
  contact_name text,
  phone text,
  regions text,
  active boolean not null default true
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  builder_id bigint not null references public.builders(id) on delete restrict,
  name text not null,
  kind text,
  region text,
  sale_price numeric(14,2) not null,
  commission_rate numeric(6,3) not null default 6,
  available_units integer not null default 0,
  active boolean not null default true,
  unique(builder_id, name)
);

create table if not exists public.client_events (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  event_type text not null,
  title text not null,
  description text,
  old_stage text,
  new_stage text,
  metric_key text,
  occurred_at timestamptz not null default now(),
  actor text not null default 'Franklin Monteiro'
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete set null,
  kind text not null,
  starts_at timestamptz not null,
  ends_at timestamptz,
  status text not null,
  outcome text,
  notes text,
  next_action text,
  next_action_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete cascade,
  project_id bigint references public.projects(id) on delete set null,
  document_type text not null,
  file_name text not null,
  storage_path text not null,
  mime_type text,
  sha256 text,
  created_at timestamptz not null default now()
);

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete restrict,
  project_id bigint not null references public.projects(id) on delete restrict,
  vgv numeric(14,2) not null,
  commission_rate numeric(6,3) not null,
  invoice_discount numeric(6,3) not null default 0,
  bonus numeric(14,2) not null default 0,
  advance numeric(14,2) not null default 0,
  received numeric(14,2) not null default 0,
  status text not null,
  closed_at date not null,
  payment_date date
);

create table if not exists public.lead_imports (
  id bigint generated by default as identity primary key,
  file_name text not null,
  origin_type text not null,
  origin_detail text,
  total_rows integer not null default 0,
  valid_rows integer not null default 0,
  duplicate_rows integer not null default 0,
  invalid_rows integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.client_sources (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  origin_type text not null,
  origin_detail text,
  project_interest text,
  source_file text,
  source_row text,
  created_at timestamptz not null default now(),
  unique(client_id, origin_type, origin_detail, project_interest, source_file)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete cascade,
  kind text not null,
  title text not null,
  body text,
  due_at timestamptz,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_portfolios (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  assigned_date date not null,
  status text not null default 'Pendente',
  attempts integer not null default 0,
  last_result text,
  assigned_at timestamptz not null default now(),
  unique(client_id, assigned_date)
);

create index if not exists idx_clients_stages on public.clients(funnel_stage, finance_stage, post_sale_stage);
create index if not exists idx_events_client_date on public.client_events(client_id, occurred_at desc);
create index if not exists idx_appointments_date on public.appointments(starts_at, status);
create index if not exists idx_notifications_due on public.notifications(read_at, due_at);
create index if not exists idx_daily_portfolio_date on public.daily_portfolios(assigned_date, status);

alter table public.clients enable row level security;
alter table public.builders enable row level security;
alter table public.projects enable row level security;
alter table public.client_events enable row level security;
alter table public.appointments enable row level security;
alter table public.documents enable row level security;
alter table public.sales enable row level security;
alter table public.lead_imports enable row level security;
alter table public.client_sources enable row level security;
alter table public.notifications enable row level security;
alter table public.daily_portfolios enable row level security;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'crm-documentos',
  'crm-documentos',
  false,
  104857600,
  array['application/pdf', 'image/jpeg', 'image/png']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
