create table if not exists public.whatsapp_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  provider text not null default 'baileys',
  status text not null default 'created' check (status in ('created','waiting_qr','connecting','connected','reconnecting','disconnected','failed','logged_out')),
  provider_identity text,
  qr_expires_at timestamptz,
  connected_phone text,
  last_connected_at timestamptz,
  last_activity_at timestamptz,
  heartbeat_at timestamptz,
  reconnect_attempts integer not null default 0,
  circuit_state text not null default 'closed' check (circuit_state in ('closed','open','half_open')),
  circuit_open_until timestamptz,
  failure_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists idx_whatsapp_sessions_active_user on public.whatsapp_sessions(user_id)
  where status <> 'logged_out';

create table if not exists public.whatsapp_auth_state (
  session_id uuid not null references public.whatsapp_sessions(id) on delete cascade,
  record_type text not null,
  record_id text not null,
  ciphertext text not null,
  iv text not null,
  auth_tag text not null,
  key_version smallint not null default 1,
  updated_at timestamptz not null default now(),
  primary key(session_id, record_type, record_id)
);
create index if not exists idx_whatsapp_auth_state_session on public.whatsapp_auth_state(session_id);

create table if not exists public.whatsapp_conversations (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.whatsapp_sessions(id) on delete cascade,
  client_id bigint references public.clients(id) on delete set null,
  provider_conversation_id text not null,
  phone_e164 text,
  provider_identity text,
  control_mode text not null default 'auto' check (control_mode in ('auto','human_takeover','observe_only','paused')),
  takeover_at timestamptz,
  takeover_by text,
  takeover_reason text,
  last_inbound_at timestamptz,
  last_outbound_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(session_id, provider_conversation_id)
);
create index if not exists idx_whatsapp_conversations_client on public.whatsapp_conversations(client_id, updated_at desc);

create table if not exists public.whatsapp_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.whatsapp_conversations(id) on delete cascade,
  client_id bigint references public.clients(id) on delete set null,
  provider_message_id text not null unique,
  direction text not null check (direction in ('inbound','outbound')),
  message_type text not null default 'text' check (message_type in ('text','audio','image','document','video','system')),
  body text,
  media_id text,
  status text not null check (status in ('received','queued','sent','delivered','read','failed','simulated')),
  idempotency_key text,
  provider_timestamp timestamptz,
  error_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists idx_whatsapp_messages_outbound_idempotency
  on public.whatsapp_messages(idempotency_key) where idempotency_key is not null;
create index if not exists idx_whatsapp_messages_conversation on public.whatsapp_messages(conversation_id, created_at desc);

create table if not exists public.agent_persona_config (
  id smallint primary key default 1 check (id = 1),
  persona_name text not null default 'Monteiro — Corretor de Imóveis',
  tone jsonb not null default '{"directness":8,"formality":6,"didacticism":8,"persuasion":7,"humor":2,"emojiUsage":3,"messageLength":5}'::jsonb,
  sales jsonb not null default '{"commercialIntensity":7,"objectionHandling":8,"closingIntensity":7,"followupIntensity":8,"reactivationIntensity":7}'::jsonb,
  contact_naming jsonb not null default '{"enabled":true,"separator":" - ","suffix":"LEADS DNA","preferCustomerProvidedName":true,"fallbackToWhatsappProfileName":true,"fallbackToCrmName":true,"syncPhone":true}'::jsonb,
  updated_at timestamptz not null default now()
);
insert into public.agent_persona_config(id) values (1) on conflict (id) do nothing;

alter table public.whatsapp_sessions enable row level security;
alter table public.whatsapp_auth_state enable row level security;
alter table public.whatsapp_conversations enable row level security;
alter table public.whatsapp_messages enable row level security;
alter table public.agent_persona_config enable row level security;
revoke all on public.whatsapp_sessions, public.whatsapp_auth_state, public.whatsapp_conversations, public.whatsapp_messages, public.agent_persona_config from public, anon, authenticated;
grant all on public.whatsapp_sessions, public.whatsapp_auth_state, public.whatsapp_conversations, public.whatsapp_messages, public.agent_persona_config to service_role;
